### PR TITLE
Update Validation of MediaAlly.php Trait

### PR DESCRIPTION
**Pull request by cw-alihyder**
It was giving an error on `$request->file` I just make it to validate whether the given parameter is actually an instance of the upload file or not.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
@cw-alihyder What error was it giving?

**Comment by cw-alihyder** [comment]
it's not letting the user go to next keep throwing the Exception even if it's a file Instance.

**Comment by unicodeveloper** [comment]
So how does your PR fix it? @cw-alihyder

**Comment by cw-alihyder** [comment]
now my PR fixes this by validating whether the param is actually an instance of  `UploadedFile` or not.  If it will not instance of `UploadedFile` it will throw an exception. On the other hand, file_exist doesn't work with the `UploadFile` instance.

**Review by unicodeveloper — APPROVED** [review]

**Pull request merged**
